# Project
version = 0.6.10
versioning.stage = alpha
java_major = 25

# Libraries
asm_version = 9.10.1
cleanmix_version = 0.7.2
mixinextras_version = 0.5.5

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = true
org.gradle.configuration-cache.problems = warn
