package com.cleanroommc.client.sdl.input;

import org.lwjgl.sdl.SDLMouse;

/** SDL's stock cursors. */
public enum SystemCursor {

    DEFAULT(SDLMouse.SDL_SYSTEM_CURSOR_DEFAULT),
    TEXT(SDLMouse.SDL_SYSTEM_CURSOR_TEXT),
    WAIT(SDLMouse.SDL_SYSTEM_CURSOR_WAIT),
    CROSSHAIR(SDLMouse.SDL_SYSTEM_CURSOR_CROSSHAIR),
    PROGRESS(SDLMouse.SDL_SYSTEM_CURSOR_PROGRESS),
    POINTER(SDLMouse.SDL_SYSTEM_CURSOR_POINTER),
    NOT_ALLOWED(SDLMouse.SDL_SYSTEM_CURSOR_NOT_ALLOWED),
    MOVE(SDLMouse.SDL_SYSTEM_CURSOR_MOVE),
    NWSE_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_NWSE_RESIZE),
    NESW_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_NESW_RESIZE),
    EW_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_EW_RESIZE),
    NS_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_NS_RESIZE),
    NW_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_NW_RESIZE),
    N_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_N_RESIZE),
    NE_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_NE_RESIZE),
    E_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_E_RESIZE),
    SE_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_SE_RESIZE),
    S_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_S_RESIZE),
    SW_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_SW_RESIZE),
    W_RESIZE(SDLMouse.SDL_SYSTEM_CURSOR_W_RESIZE);

    private final int value;

    SystemCursor(int value) {
        this.value = value;
    }

    int value() {
        return value;
    }

}
