# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and Release Installer

on: 
  workflow_call:

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3.10.0
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Fix Gradle Permission
      run: chmod +x ./gradlew
        
    - name: Setup Forge env
      run: ./gradlew setup
      
    - name: Shutdown Gradle # FG3+ dumb stuff hahahaha
      run: ./gradlew --stop
        
    - name: Build Forge Jar File
      run: ./gradlew universalJar
    - name: Build Forge Installer
      run: ./gradlew installerJar
        
    - name: Release Forge Installer
      uses: actions/upload-artifact@v3.1.2
      with:
        name: installer
        path: projects/cleanroom/build/libs/*-installer.jar
        
  release:
    name: Retrieve Artifact and Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        
      - name: Create GitHub Release
        uses: KorewaLidesu/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest #TODO
          commitish: ${{ github.ref.name }}
          body: "" #TODO
          name:  1.0.0.0 #TODO
          prerelease: false
          allow_override: true
          gzip: false
          files: |
              ./installer/*-installer.jar
