# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build and Upload Test Artifact For Pull Request

on:
  pull_request:
  workflow_dispatch:
    inputs:
      build_type:
        type: choice
        description: Build type
        options:
          - Stable
          - Experimental
          - Bleeding Edge

permissions:
  contents: read

jobs:
  build:
    name: Build and Upload Artifact For Pull Request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      # add more feat here if required
      - name: Gather build info
        id: vars
        run: |
          BRANCH_FEAT=$(echo "${{ steps.branch-names.outputs.current_branch }}" | cut -d'/' -f1 | awk '{print tolower($0)}')
          if [ "$BRANCH_FEAT" = "experimental" ]; then
            echo "BUILD_TYPE=Experimental" >> $GITHUB_OUTPUT
          elif [ "$BRANCH_FEAT" = "bleeding-edge" ]; then
            echo "BUILD_TYPE=Bleeding Edge" >> $GITHUB_OUTPUT
          else
            echo "BUILD_TYPE=Stable" >> $GITHUB_OUTPUT
          fi

      - name: Fix Gradle permission
        run: chmod +x ./gradlew

      - name: Setup Forge env
        run: ./gradlew setup
      - name: Stop Gradle daemon
        run: ./gradlew --stop

      - name: Build Forge Installer Jar
        run: ./gradlew installerJar

      - name: Upload Forge Universal
        uses: actions/upload-artifact@v4.3.3
        with:
          name: universal
          path: projects/cleanroom/build/libs/*-universal.jar

      - name: Upload Forge Installer
        id: upload-job
        uses: actions/upload-artifact@v4.3.3
        with:
          name: installer
          path: projects/cleanroom/build/libs/*-installer.jar
          if-no-files-found: error