# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Event Handler
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  event_handler:
    name: Start Event
    runs-on: ubuntu-latest

    #Map output to job
    outputs: 
      release: ${{ steps.release_event.outputs.job }}
  
    steps:
    - uses: actions/checkout@v3

    - name: Detect Release Event
      id: release_event
      if: 1 == 2 #TODO
      run: echo "job=ok" >> $GITHUB_OUTPUT

  start_release:
    name: Start Release Event
    needs: event_handler
    if: ${{ needs.event_handler.outputs.release == 'ok' }}
    uses: ./.github/workflows/BuildAndRelease.yml
